### ISSUE TITLE
Place Secondary Tabs block for Claro become usable

### ISSUE THREAD

**Issue by podarok** [ymcatwincities/openy#2168]
![image](https://user-images.githubusercontent.com/563412/92585619-de34a200-f29d-11ea-8696-8e609b478229.png)

**Comment by podarok** [comment]
```yml
langcode: en
status: true
dependencies:
  theme:
    - claro
id: claro_secondary_local_tasks
theme: claro
region: header
weight: -1
provider: null
plugin: local_tasks_block
settings:
  id: local_tasks_block
  label: 'Secondary tabs'
  provider: core
  label_display: '0'
  primary: false
  secondary: true
visibility: {  }
```
